name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version:[3.6]
      steps:
        - uses: actions/checkout@v1
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip setuptools wheel
            python -m pip install --upgrade setuptools-rust
        - name: Build wheel
          run: |
            python setup.py bdist_wheel
